name: cassie

channels:
  - conda-forge

dependencies:
  - clang
  - clang-tools
  - python-clang
  - python=3.6
  - ipython
  - numpy
  - scipy
  - matplotlib
  - pygame
  - pip
  - pip:
    - pygame
    - git+https://github.com/samarth-robo/ctypeslib.git
